apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-keys-backup
  namespace: sealed-secrets-keys-backup
  labels:
    app: sealed-secrets-keys-backup
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets-keys-backup
      component: worker
  template:
    metadata:
      labels:
        app: sealed-secrets-keys-backup
        component: worker
    spec:
      serviceAccountName: sealed-secrets-keys-backup
      containers:
      - name: sealed-secrets-keys-backup
        image: bloveless/sealed-secrets-keys-backup
        volumeMounts:
        - name: backups
          mountPath: /backups
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: sealed-secrets-keys-backup-backups

