---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-keys-backup
  namespace: sealed-secrets-keys-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-keys-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-keys-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secrets-keys-reader
subjects:
- kind: ServiceAccount
  name: sealed-secrets-keys-backup
  namespace: sealed-secrets-keys-backup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-keys-backup
  namespace: sealed-secrets-keys-backup
  labels:
    app: sealed-secrets-keys-backup
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets-keys-backup
      component: worker
  template:
    metadata:
      labels:
        app: sealed-secrets-keys-backup
        component: worker
    spec:
      serviceAccountName: sealed-secrets-keys-backup
      containers:
      - name: sealed-secrets-keys-backup
        image: bloveless/sealed-secrets-keys-backup

