apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-system-sealed-secrets-keys-backup-backups
  labels:
    type: local
    app: sealed-secrets-keys-backup
    component: sealed-secrets-keys-backup
    volume: backups
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.4.245
    path: /volume1/k8s/kube-system/sealed-secrets-keys-backup/backups
  mountOptions:
    - nfsvers=4.1

