apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sealed-secrets-keys-backup-backups
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: sealed-secrets-keys-backup
      component: sealed-secrets-keys-backup
      volume: backups
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
