name: sealed-secrets-keys-backup-ci

on:
  workflow_dispatch:
  push:
    tags:
      - 'sealed-secrets-keys-backup-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Tag Version
        id: get-tag-version
        run: |
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\/sealed-secrets-keys-backup-/}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./sealed-secrets-keys-backup
          file: ./sealed-secrets-keys-backup/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "bloveless/sealed-secrets-keys-backup:${{steps.get-tag-version.outputs.tag}}"
